name: fieldsales
description: Fingertipplus Technologies is an international team where development powers meet entrepreneurship. We have worked together for many years in different functions. All the time we noticed that with Salesforce ecosystem growing, there was a strong need for skilled developers. This is why we founded Fingertipplus Technologies to offer this service to our customers.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  configurable_expansion_tile_null_safety: ^3.3.2
  cupertino_icons: ^1.0.8
  date_field: ^5.0.1
  dotted_border: ^2.1.0
  drift: ^2.18.0
  dropdown_search: ^5.0.6
  entry: ^1.0.0
  file_picker: ^8.0.3
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  flutter_debug_overlay: ^0.1.8
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.2.2
  flutter_screenutil: ^5.9.3
  flutter_smart_dialog: ^4.9.8
  hive_flutter: ^1.1.0
  http: ^1.2.1
  image_picker: ^1.1.1
  internet_connection_checker_plus: ^2.4.1
  intl: ^0.19.0
  ios_keyboard_action: ^0.0.7
  json_annotation: ^4.9.0
  json_cache: ^3.0.1
  location: ^6.0.2
  mobile_device_identifier: ^0.0.2
  navigation_history_observer: ^1.1.1
  open_app_settings: ^2.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  readmore: ^3.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  sqlite3_flutter_libs: ^0.5.22
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  synchronized: ^3.1.0+1
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  stacked_generator: ^1.6.0
  flutter_gen_runner: ^5.5.0+1
  drift_dev: ^2.18.0
  json_serializable: ^6.8.0
  change_app_package_name: ^1.1.0

dependency_overrides:
  web: ^0.5.0

flutter_gen:
  output: lib/ui/common/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ca/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
        - asset: assets/fonts/Lato-SemiBold.ttf
        - asset: assets/fonts/Lato-SemiBoldItalic.ttf

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
